version: '3'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.39.1
    ports:
      - 9000:9090
    volumes:
      - ./configs/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.1
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./configs/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  grafana-data:

networks:
  mon-observability-net: